include(CheckCXXCompilerFlag)

if((CMAKE_CXX_COMPILER_ID MATCHES "GNU") OR (CMAKE_CXX_COMPILER_ID MATCHES "Clang"))
    set(OPTIONS -Werror -Wall -Wextra -Wpedantic)
elseif(CMAKE_CXX_COMPILER_ID MATCHES "MSVC")
    set(OPTIONS /W4 /WX)
    if(HAS_PERMISSIVE_FLAG)
        set(OPTIONS ${OPTIONS} /permissive-)
    endif()
endif()

function(make_example target libs)
    add_executable(${target} ${target}.cpp)
    set_target_properties(${target} PROPERTIES CXX_EXTENSIONS OFF)
    #target_compile_features(${target} PRIVATE cxx_std_17)
    target_compile_options(${target} PRIVATE ${OPTIONS})
    target_link_libraries(${target} PRIVATE ${CMAKE_PROJECT_NAME} ${libs})
endfunction()

make_example(example "")
make_example(simple_fsm "")

if(Boost_FOUND)
    add_executable(asio_fsm asio_fsm.cpp)
    set_target_properties(asio_fsm PROPERTIES CXX_EXTENSIONS OFF)
    target_compile_options(asio_fsm PRIVATE ${OPTIONS})
    target_include_directories(asio_fsm PRIVATE ${Boost_INCLUDE_DIRS})
    target_link_libraries(asio_fsm PRIVATE ${CMAKE_PROJECT_NAME} date::date-tz)

    if(TARGET Boost::headers)
        target_link_libraries(asio_fsm PRIVATE Boost::headers)
    endif()

    if(TARGET Boost::system)
        target_link_libraries(asio_fsm PRIVATE Boost::system)
    endif()

    if(TARGET Boost::thread)
        target_link_libraries(asio_fsm PRIVATE Boost::thread)
    endif()
endif()