include(CheckCXXCompilerFlag)

include(CTest)
include(Catch)

if(CMAKE_CXX_COMPILER_ID MATCHES "MSVC")
    set(COMPILE_OPTIONS /W4 /WX)
    set(LINK_OPTIONS )
    check_cxx_compiler_flag(/permissive HAS_PERMISSIVE_FLAG)
    if(HAS_PERMISSIVE_FLAG)
    set(COMPILE_OPTIONS ${COMPILE_OPTIONS} /permissive-)
    endif()

    check_cxx_compiler_flag(/std:c++20 HAS_CPP20_FLAG)
    check_cxx_compiler_flag(/std:c++latest HAS_CPPLATEST_FLAG)
elseif(CMAKE_CXX_COMPILER_ID MATCHES "GNU|Clang")
    set(CMAKE_VERBOSE_MAKEFILE ON)
    set(COMPILE_OPTIONS -Wall -Wextra -pedantic-errors)
    set(LINK_OPTIONS )
     check_cxx_compiler_flag(-std=c++20 HAS_CPP20_FLAG)
endif()


# Coverage flags for Clang
if(COVERAGE AND CMAKE_CXX_COMPILER_ID MATCHES "Clang")
    set(COVERAGE_FLAGS -fprofile-instr-generate -fcoverage-mapping)
    set(COMPILE_OPTIONS ${COMPILE_OPTIONS} ${COVERAGE_FLAGS})
    set(LINK_OPTIONS ${LINK_OPTIONS} ${COVERAGE_FLAGS})
endif()

# Global property to collect all test targets
set_property(GLOBAL PROPERTY FSM_TEST_TARGETS "")


function(assign_test src lib std)
    get_filename_component(target ${src} NAME_WE)
    add_executable(${target} ${src})
    target_compile_options(${target} PRIVATE ${COMPILE_OPTIONS})
    target_link_libraries(${target} PRIVATE ${lib} Catch2::Catch2WithMain)
    target_link_options(${target} PRIVATE ${LINK_OPTIONS})
    set_target_properties(${target} PROPERTIES CXX_EXTENSIONS OFF)
    if(std)
        if(CMAKE_CXX_COMPILER_ID MATCHES "MSVC")
            target_compile_options(${target} PRIVATE /std:${std})
        else()
            target_compile_options(${target} PRIVATE -std=${std})
        endif()
    endif()
    # Register target name for global test target list
    set_property(GLOBAL APPEND PROPERTY FSM_TEST_TARGETS ${target})
    catch_discover_tests(${target} TEST_PREFIX ${lib}_ TEST_SUFFIX _${std} ADD_TAGS_AS_LABELS)
endfunction()


function(assign_test_with_libs src lib std libs)
    get_filename_component(target ${src} NAME_WE)
    add_executable(${target} ${src})
    target_compile_options(${target} PRIVATE ${COMPILE_OPTIONS})
    target_link_libraries(${target} PRIVATE ${lib} ${libs} Catch2::Catch2WithMain)
    target_link_options(${target} PRIVATE ${LINK_OPTIONS})
    set_target_properties(${target} PROPERTIES CXX_EXTENSIONS OFF)
    if(std)
        if(CMAKE_CXX_COMPILER_ID MATCHES "MSVC")
            target_compile_options(${target} PRIVATE /std:${std})
        else()
            target_compile_options(${target} PRIVATE -std=${std})
        endif()
    endif()
    set_property(GLOBAL APPEND PROPERTY FSM_TEST_TARGETS ${target})
    catch_discover_tests(${target} TEST_PREFIX ${lib}_ TEST_SUFFIX _${std} ADD_TAGS_AS_LABELS)
endfunction()


function(assign_test_with_includes src lib std include_dirs)
    get_filename_component(target ${src} NAME_WE)
    add_executable(${target} ${src})
    target_compile_options(${target} PRIVATE ${COMPILE_OPTIONS})
    target_include_directories(${target} PRIVATE ${include_dirs})
    target_link_libraries(${target} PRIVATE ${lib} Catch2::Catch2WithMain)
    target_link_options(${target} PRIVATE ${LINK_OPTIONS})
    set_target_properties(${target} PROPERTIES CXX_EXTENSIONS OFF)
    if(std)
        if(CMAKE_CXX_COMPILER_ID MATCHES "MSVC")
            target_compile_options(${target} PRIVATE /std:${std})
        else()
            target_compile_options(${target} PRIVATE -std=${std})
        endif()
    endif()
    set_property(GLOBAL APPEND PROPERTY FSM_TEST_TARGETS ${target})
    catch_discover_tests(${target} TEST_PREFIX ${lib}_ TEST_SUFFIX _${std} ADD_TAGS_AS_LABELS)
endfunction()